In [1]:
import requests
import pandas as pd
from datetime import datetime

In [2]:
API_KEY = "636f32401eac7aba09a854f8a5376377"
cities = ["Lagos", "London", "New York"]

weather_data = []

for city in cities:
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)
    data = response.json()

    weather_data.append({
     "city": data["name"],
     "temperature": data["main"]["temp"],
     "humidity": data["main"]["humidity"], 
     "condition": data["weather"][0]["description"],
     "wind_speed": data["wind"]["speed"],
     "datetime": datetime.now().strftime("%Y-%m-%d %H:%M:%S")      
    })

    df = pd.DataFrame(weather_data)

In [3]:
 df.head()

,city,temperature,humidity,condition,wind_speed,datetime
0,Lagos,26.67,86,overcast clouds,3.15,2026-07-15 13:49:36
1,London,27.30,51,clear sky,4.47,2026-07-15 13:49:37
2,New York,28.72,68,scattered clouds,4.92,2026-07-15 13:49:39

In [4]:
df.dtypes

city            object
temperature    float64
humidity         int64
condition       object
wind_speed     float64
datetime        object
dtype: object

In [5]:
df["datetime"] = pd.to_datetime(df["datetime"])
df["temperature"] = df["temperature"].round(1)
df["condition"] = df["condition"].str.title()

In [6]:
df.dtypes

city                   object
temperature           float64
humidity                int64
condition              object
wind_speed            float64
datetime       datetime64[ns]
dtype: object

In [7]:
df.head()

,city,temperature,humidity,condition,wind_speed,datetime
0,Lagos,26.7,86,Overcast Clouds,3.15,2026-07-15 13:49:36
1,London,27.3,51,Clear Sky,4.47,2026-07-15 13:49:37
2,New York,28.7,68,Scattered Clouds,4.92,2026-07-15 13:49:39

In [8]:
df.to_csv("weather_data.csv", index=False)
print("done")

done

In [9]:
df = pd.read_csv("weather_data.csv")

In [10]:
df.head()

,city,temperature,humidity,condition,wind_speed,datetime
0,Lagos,26.7,86,Overcast Clouds,3.15,2026-07-15 13:49:36
1,London,27.3,51,Clear Sky,4.47,2026-07-15 13:49:37
2,New York,28.7,68,Scattered Clouds,4.92,2026-07-15 13:49:39

In [11]:
hottest = df.loc[df["temperature"].idxmax()]
print(f"Hottest city: {hottest['city']} at {hottest['temperature']}C")

Hottest city: New York at 28.7C

In [12]:
most_humid = df.loc[df["humidity"].idxmax()]
print(f"Most Humid city: {most_humid['city']} at {most_humid['humidity']}%")

Most Humid city: Lagos at 86%

In [13]:
print("\nWeather conditions:")
print(df[["city", "condition"]])

Weather conditions:
       city         condition
0     Lagos   Overcast Clouds
1    London         Clear Sky
2  New York  Scattered Clouds